# Generated by Django 5.2.6 on 2025-09-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vehicle_created_at_vehicle_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
